// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'your existing web config in index.html will be used instead.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // NOTE: Download google-services.json from Firebase Console 
  // and place it in android/app/ to ensure this config matches your project.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADp30eyREuq3RGw3ddoOd0q_wkKOYqoyw',
    appId: '1:997802400886:android:5a3fa4d711a7c67e9e1357',
    messagingSenderId: '997802400886',
    projectId: 'flutter-auth-app-ca270',
    storageBucket: 'flutter-auth-app-ca270.firebasestorage.app',
  );

  // NOTE: Download GoogleService-Info.plist from Firebase Console 
  // and place it in ios/Runner/ then update these values.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '[YOUR-IOS-API-KEY]',
    appId: '[YOUR-IOS-APP-ID]',
    messagingSenderId: '[YOUR-SENDER-ID]',
    projectId: 'flutter-auth-app-ca270',
    storageBucket: 'flutter-auth-app-ca270.firebasestorage.app',
    iosBundleId: 'com.linkspec.linkspec_app',
  );
}

